#!/usr/bin/env bash
# Check if the load balancer is accepting HTTPS traffic

# Replace "www.yourdomain.com" with your actual domain
DOMAIN="www.shyakx.tech.com"

# Use curl to make an HTTP request and check the status code
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$DOMAIN)

# Compare the obtained HTTP status with the expected value
EXPECTED_STATUS="200"

if [ "$HTTP_STATUS" = "$EXPECTED_STATUS" ]; then
    echo "Your load balancer is accepting HTTPS traffic with status code: $HTTP_STATUS"
else
    echo "Execution not successful"
    echo "Expected: $EXPECTED_STATUS"
    echo "Got: $HTTP_STATUS"
fi
